/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'JuanCarlosPuerto' at '18/09/16 12:22 PM' with Gradle 2.14.1
 *
 * @author JuanCarlosPuerto, @date 18/09/16 12:22 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
