import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'JuanCarlosPuerto' at '18/09/16 12:22 PM' with Gradle 2.14.1
 *
 * @author JuanCarlosPuerto, @date 18/09/16 12:22 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
